---
title: Will Pan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
enforce_ssl: willpan.xyz
highlighter: rouge
livereload: true
lsi: false
markdown: kramdown
port: 3000
url: https://willpan.xyz
gems: [jekyll-paginate] 
owner:
  name: Will Pan
  login: will
  email: vpan@foxmail.com
  