# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: de_DE
destination: ../htdocs/
title: Fiese Info
email: fiese-info@fiese.info
description:  "Fiese Infos.<br>  Von einem Fiesen Typ."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fiese.info" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/logo/logo-128.ico # path of site logo, e.g. "/images/logo.png"
github_username:  Chi110r
timezone: Europa/Berlin
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: "UA-104941731-3"

# Liquid
liquid:
  error_mode: strict


# Build settings
markdown: kramdown
port: 3000
url: https://www.fiese.info

paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate


# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
    
 
# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true
      
enforce_ssl: www.fiese.info
highlighter: rouge
livereload: true
lsi: false
theme: jekyll-theme-so-simple  
  
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Andreas Fies
  picture: /images/profile.jpg
  email: fiese-info@fiese.info
  street: Jakobstraße 24
  zip: 73760
  city: Ostfildern
  twitter: None
  links: 
  - title: Andy's site
    url: http://www.fiese.info
    con: /images/logo/logo-32.ico 
  - title: Instagram
    url: https://instagram.com/richardfies
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/Chi110r
    icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Will's site
    url: http://www.fiese.info
    con: /images/logo/logo-32.ico 
  - title: Instagram
    url: https://instagram.com/richardfies
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/Chi110r
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
